name: workflow for Python using Snyk security scan
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: awshole/snyk-python@v1.1.0
        with:
          snyk_api_key: ${{ secrets.SNYK_TOKEN }}
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
