name: Python Interview Test

on:
  workflow_dispatch:
    inputs:
      change_order:
        description: "Please add CHG######"
        required: true
        default: ""
  push:
    branches: [ 'main', 'develop']
    


jobs:
  deploy_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: python test.py

