name: Practice Workflow to perform security scans

on:
  workflow-dispatch:
  push:
    branches:
      - develop
      - main
  pull-request:
    branches:
      - develop
      - main

jobs:
  security scanning:
    runs-on: ubuntu-latest
    steps:
      - name: Setting up pythong
        uses: actions/checkout@v4
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      run: python test.py
